# Generated by Django 5.2.3 on 2025-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_setactivities_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineactivities',
            name='line_name',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
